fos_elastica:
    clients:
        node0: { host: %tms_search_host%, port: %tms_search_port% }
    indexes:
        participations:
            client: node0
            types:
                participation:
                    mappings:
                        firstName: { type: string }
                        lastName: { type: string }
                        zipCode: { type: integer }
                        msDataRef: { type: string }
                        gender: { type: string }
                        phone: { type: string }