services:
    tms_search.indexer.elasticsearch:
        class: Tms\Bundle\SearchBundle\SearchIndexer\ElasticSearchIndexer

 #   tms_search.indexer.lucenesearch:
 #       class: Tms\Bundle\SearchBundle\SearchIndexer\LuceneSearchIndexer

    tms_search.handler:
        class: Tms\Bundle\SearchBundle\Handler\SearchIndexHandler
        arguments: [ @doctrine_mongodb ]