parameters:
    tms_search_default_query_limit: 10

services:
    tms_search.indexer.elasticsearch:
        class: Tms\Bundle\SearchBundle\SearchIndexer\ElasticSearchIndexer
        abstract: true

 #   tms_search.indexer.lucenesearch:
 #       class: Tms\Bundle\SearchBundle\SearchIndexer\LuceneSearchIndexer

    tms_search.handler:
        class: Tms\Bundle\SearchBundle\Handler\SearchIndexHandler
        arguments: []
