services:
    tms_search.elasticsearch:
        class: Tms\Bundle\SearchBundle\SearchIndexer\ElasticSearchIndexer
        arguments: [@tms_search.elasticsearch.client]
        tags:
            - { name: tms_search.provider }

    tms_search.elasticsearch.client:
        class: Elasticsearch\Client
        tags:
            - { name: tms_search.provider.elasticsearch }

    tms_search.handler:
        class: Tms\Bundle\SearchBundle\Handler\SearchIndexHandler
        arguments: [ @doctrine_mongodb ]