services:
    tms_search.adapted_index:
        class: Tms\Bundle\SearchBundle\Index\AdaptedIndex

    tms_search.elasticsearch:
        class: Tms\Bundle\SearchBundle\Index\Elasticsearch
        arguments: [@tms_search.elasticsearch.client]
        tags:
            - { name: tms_search.provider }

    tms_search.elastica:
        class: Tms\Bundle\SearchBundle\Index\Elastica
        tags:
            - { name: tms_search.provider }

    tms_search.elasticsearch.client:
        class: Elasticsearch\Client
        tags:
            - { name: tms_search.provider.elasticsearch }
